DUS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('accounts/', include("accounts.urls", namespace='accounts')),
]

accounts/urls.py
from django.urls import path, include
from .views import signup_view, login_view, logout_view


app_name = 'accounts'


urlpatterns = [
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('signup/', signup_view, name="signup")
]

mainApp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views 
from .views import home, redirection, shorten, dashboard, contactus, aboutus


urlpatterns = [
    path('', home, name="Homepage"),
    path('short', shorten, name="Shorten URL"),
    path('<str:url>', redirection, name="Redirection To Original Page"),
    path('dashboard/', dashboard, name="DUS Dashboard"),
    path('aboutus/', aboutus, name="aboutus"),
    path('contactus/', contactus, name="contactus"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainApp/models.py
from django.db import models
from django.contrib.auth.models import User

class Keys(models.Model):
    id = models.AutoField(primary_key=True)
    key = models.CharField(max_length=6)

    def __str__(self):
        return self.key


class ShortenUrl(models.Model):
    id = models.AutoField(primary_key=True)
    original_url = models.CharField(blank=False, max_length=200)
    short_url = models.CharField(blank=False, max_length=30, unique=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    updation_date = models.DateTimeField(auto_now=True)
    expiration_date = models.DateTimeField(auto_now=False)
    expire_flag = models.BooleanField(default=False)
    visits = models.IntegerField(default=0)

    def __str__(self):
        return self.short_url 


class ContactUs(models.Model):
    issues_choices = (('Report a bug','Report a bug'),('Feature Request','Feature Request'),('Enhancement','Enhancement'),)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    issue = models.CharField(max_length=100, choices=issues_choices, default='Report a bug')
    message = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    updation_date = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name + ' | ' + str(self.message)[:200]


class DashboardStats(models.Model):
    id = models.AutoField(primary_key=True)
    shorten_id = models.ForeignKey(ShortenUrl, default=15, on_delete=models.CASCADE)
    click_datetime = models.DateTimeField(auto_now_add=True)
    ip_address = models.CharField(max_length=100)
    user_agent = models.CharField(max_length=255)
    country = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    browser = models.CharField(max_length=100)
    os = models.CharField(max_length=100)
    device = models.CharField(max_length=100)
    referrer_url = models.CharField(max_length=255)
    clicks = models.IntegerField(default=0)

mainApp/forms.py
from django import forms
from .models import ContactUs
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class ContactUsForm(forms.ModelForm):
    name = forms.CharField(max_length=255)
    terms_and_conditions = forms.BooleanField()
    class Meta:
        model = ContactUs
        fields = '__all__'

        

    def save(self, commit=True):
        contactus = super().save(commit=False)
        if commit:
            contactus.save()
        return contactus

mainApp/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Keys, ShortenUrl, ContactUs, DashboardStats
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib import auth
from .forms import ContactUsForm
import accounts.urls
import random
import string
from django.utils import timezone
from datetime import datetime, timedelta
import os
from django.conf import settings

USED_FOR_MAPPING = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_-"

def get_url():
	print(len(USED_FOR_MAPPING))
	res = set()
	for i in range(pow(100,3)):
		n = i
		curr = ""
		for j in range(3):
			curr+=USED_FOR_MAPPING[n%64]
			n//= 64
		res.add(curr)

	return res


def home(request):
    # print(request.META['HTTP_HOST'])
    # res = get_url()
    # for it in res:
    #     k = Keys(key=it)
    #     k.save()
    return render(request, "index.html")


@login_required(login_url='/accounts/login/')
def dashboard(request):
    user = request.user
    context = {}
    all_urls = ShortenUrl.objects.filter(user=user)

    context['all_urls'] = all_urls

    return render(request, "dashboard.html", context)

def redirection(request, url):
    short_url = str(request.META['HTTP_HOST']) + request.path
    print(short_url)
    try:
        check = ShortenUrl.objects.get(short_url=short_url)
        if(check.expire_flag == False or datetime.now() < check.expiration_date):
            check.visits += 1
            check.save()

            return redirect(check.original_url)
        else:
            check.expire_flag = True
            return render(request, 'expired.html')
    except ShortenUrl.DoesNotExist:
        messages.error(request, "The URL you are trying to reach has been expired or it is not yet created.")
        return redirect("/")


def shorten(request):
    if request.method == "POST":
        if request.POST['original_url'] and request.POST['custom_url']:
            original = request.POST['original_url']
            org_url = ShortenUrl.objects.filter(original_url=original).exists()
            if org_url:
                url = ShortenUrl.objects.get(original_url=original)
                context = {
                    "short_url": url,
                }
                messages.error(request, "Short URL already exists. Please use the below URL.")
                return render(request, 'index.html', context)
            else:
                original = request.POST['original_url']
                expiry_days = 7

                short = str(request.META['HTTP_HOST']) + "/" + str(request.POST['custom_url'])
                check = ShortenUrl.objects.filter(short_url=short)
                if not check:
                    newurl = ShortenUrl(
                        original_url=original,
                        short_url=short,
                        user=request.user,
                        creation_date=datetime.now(),
                        expiration_date=datetime.now() + timedelta(days=expiry_days)
                    )
                    newurl.save()
                    context = {
                        "short_url": short,
                    }
                    return render(request, 'index.html', context)
                else:
                    messages.error(request, "Custom URL already exists. Please use a different path.")
                    return render(request, 'index.html', {'error': 'Custom URL already exists'})
        elif request.POST['original_url']:
            original = request.POST['original_url']
            expiry_days = 7
            org_url = ShortenUrl.objects.filter(original_url=original).exists()
            if org_url:
                url = ShortenUrl.objects.get(original_url=original)
                context = {
                    "short_url": url,
                }
                return render(request, 'index.html', context)
            else:
                
                short = str(request.META['HTTP_HOST'])
                key = Keys.objects.last()
                short += "/" + key.key
                key.delete()
                newurl = ShortenUrl(original_url=original, short_url=short,
                                    creation_date=datetime.now(),
                                    expiration_date=(datetime.now() + timedelta(days=int(expiry_days))))
                newurl.save()
                context = {
                    "short_url": short,
                }
                messages.success(request, "URL created successfully. Check below")
                return render(request, 'index.html', context)
        else:
            messages.error(request, "Empty Field")
            return redirect('')
    else:
        return redirect('')


def contactus(request):
    form = ContactUsForm()
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            email = form.cleaned_data.get('email')
            issue = form.cleaned_data.get('issue')
            message = form.cleaned_data.get('message')
            
            contactus = ContactUs(name=name, email=email, issue=issue, message=message)
            contactus.save()
            messages.success(request, "Your message has been submitted sucessfully.")
        else:
            messages.error(request, "You are missing out on a field. Please fill the complete form before submitting.") 
    form = ContactUsForm()
    return render(request, "contactus.html", {'form': form})
                        
def aboutus(request):
    return render(request, "aboutus.html", {})

mainApp/templates/aboutus.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
About us
{% endblock title%}

{% block body %}

<section class="section">
    <div class="conatainer">
        <div class="columns is-centered">
            <div class="column is-half ">
                <div class="card" style="box-shadow: none;">
                    <div class="card-content">
                        <p class="is-size-2 mt-4 " style="font-weight: 500;" >Who Are We?</p>
                        <p class="subtitle is-size-6 mt-5" style="line-height: 1.4;letter-spacing: .6px;font-weight: 300;">We are a small bunch of enthusiastic students (or so called developers :D) who love to code, work on innovative projects and showcase our skills. We usually work for clients, we sometimes do work on our private products, but this was our first self-initiated open source project.</p>
                        
                        <p class="is-size-2 mt-4 " style="font-weight: 500;" >Want To Contribute?</p>
                        <p class="subtitle is-size-6 mt-5" style="line-height: 1.4;letter-spacing: .6px;font-weight: 300;">The website is fully open-source built with Python (Django Framework) and deployed on Heroku Servers (Dyno). Feel free to open up any new issue/pull request <a href="https://github.com/anonymous-sidhax/Django-URL-Shortner">here</a> </p>

                        <p class="is-size-2 mt-4 " style="font-weight: 500;" >Contact Us</p>
                        <p class="subtitle is-size-6 mt-5" style="line-height: 1.4;letter-spacing: .6px;font-weight: 300;">We are very friendly and always open to discussing new projects, interesting ideas, student work or opportunities to be part of an event. Feel free to reach out to us with any questions by sending us a mail on <i><u>dus.2020.py@gmail.com</u></i> or filling out the <a href="{% url 'contactus' %}">Contact Us Form</a></p>
                        
                    </div>
                </div>
            </div>
            <div class="column is-half has-text-centered">
                <div class="card" style="box-shadow: none;">
                    <div class="card-image"><img src="{% static 'assets/img/team.svg' %}" alt="" width="349.2"></div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock body%}

mainApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title> DUS - {% block title %} {% endblock title%}</title>   
</head>
<body>

    <style>
      #heading{
        font-size: 30px;
        font-weight: 800;
      }
    </style>
   
  {% if messages %}
  {% for message in messages %}
  {% if  message.tags == 'success' %}
  <article class="message is-success">
    <div class="message-header">
      <p>{{ message }}</p>
      
      <button class="delete" aria-label="delete"></button>
    </div>
  </article>
  {% elif message.tags == 'error' %}
  <article class="message is-danger">
    <div class="message-header">
      <p>{{ message }}</p>
      
      <button class="delete" aria-label="delete"></button>
    </div>
  </article>
  {% elif message.tags == 'info' %}
  <article class="message is-info">
    <div class="message-header">
      <p>{{ message }}</p>
      
      <button class="delete" aria-label="delete"></button>
    </div>
  </article>
  {% elif message.tags == 'warning' %}
  <article class="message is-warning">
    <div class="message-header">
      <p>{{ message }}</p>
      <button class="delete" aria-label="delete"></button>
    </div>
  </article>
  {% endif %}
  {% endfor %}
  {% endif %}



  
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <h1 id="heading"> DUS-Python </h1>
      </a>
  
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">

        <a class="navbar-item" href="{% url 'DUS Dashboard' %}">
          Dashboard
        </a>
  
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>
  
          <div class="navbar-dropdown">
            <a class="navbar-item" href="{% url 'aboutus' %}">
              About
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item" href="{% url 'contactus' %}">
              Contact Support
            </a>
          </div>
        </div>
      </div>
  
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if not user.is_authenticated %}
            <a class="button is-danger" href="{% url 'accounts:signup' %}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="{% url 'accounts:login' %}">
              Log in
            </a>
            {% else %}
            <p class="mr-2 is-size-6" >Welcome <strong>{{ request.user }}</strong></p>
            <a href="{% url 'accounts:logout' %}" class="button is-danger">Logout</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>


{% block body %}


{% endblock body %}

<footer class="footer my-5">
  <div class="content has-text-centered">
    <p>
      Copyright &copy;<strong> DUS</strong>
    </p>
  </div>
</footer>

<script>
{% if messages %}

  const message = document.querySelector('.message');
  const delete_button = document.querySelector('.delete');

  delete_button.addEventListener('click', ()=> {
    message.classList.add('is-hidden');
  })

{% endif %}

</script>

</body>
</html>

mainApp/templates/contactus.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
Contact us
{% endblock title %}

{% block body %}

<style>
  .errorlist{
    color: #f03a5f;;
  }
</style>
<section class="section">
    <div class="container">
        <div class="columns is-centered is-multiline">
            <div class="column is-full">
                <div class="card has-text-centered" style="box-shadow: none;">
                    <div class="card-content">
                        <h3 class="is-size-2 is-size-3-mobile title">Contact Us</h3>
                        <p class="subtitle is-size-6 mt-1">Get in touch with us if you have any questions</p>
                    </div>
                </div>
            </div>
            <div class="column is-half">
                <div class="card ">
                    <div class="card-content">
                        <form action="{% url 'contactus' %}" novalidate method="POST">

                              {% csrf_token %}
                              <div class="field">
                                <label class="label">Username</label>
                                <div class="control has-icons-left has-icons-right">
                                        {% render_field form.name placeholder="Username" class="input" %}
                                  <span class="icon is-small is-left">
                                    <i class="fa fa-user"></i>
                                  </span>
                                </div>
                                <p class="help is-danger">{{form.name.errors}}</p>
                              </div>
                                 
                      
                              
                              
                              <div class="field">
                                <label class="label">Email</label>
                                <div class="control has-icons-left has-icons-right">
                                    {% render_field form.email placeholder="Email Address" class="input" %}
                                  <span class="icon is-small is-left">
                                    <i class="fa fa-envelope"></i>
                                  </span>
                                </div>
                                <p class="help is-danger">{{form.email.errors}}</p>
                              </div>
                              
                              <div class="field">
                                <label class="label">Issue</label>
                                <div class="control">
                                  <div class="select ">
                                    {% render_field form.issue  %}
                                  </div>
                                </div>
                                <p class="help is-danger">{{form.issue.errors}}</p>
                              </div>
                              
                              <div class="field">
                                <label class="label">Message</label>
                                <div class="control">
                                  {% render_field form.message placeholder="Your Message" class="textarea" %}
                                </div>
                                <p class="help is-danger">{{form.message.errors}}</p>
                                
                              </div>
                              
                              <div class="field">
                                <div class="control">
                                  <label class="checkbox">
                                    {% render_field form.terms_and_conditions %}
                                    I agree to the <a href="#">terms and conditions</a>
                                  </label>
                                </div>
                                <p class="help is-danger">{{form.terms_and_conditions.errors}}</p>
                              </div>
                              
                            <div class="field my-6">
                                <div class="control">
                                    <button class="button is-rounded is-medium input is-normal is-danger">Submit</button>
                                  </div>
                            </div>
                                
                              
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock body %}

mainApp/templates/dashboard.html
{% extends 'base.html' %}
{% block title %} Home {% endblock title %}
{% block body %}
{% load static %}

<style>
    *{
        scroll-behavior: smooth;
    }
    .is-red{
        background-color: #ff3b3b;
        opacity: 0.9;
        color: #f4f4f4;
    }
    .is-red:hover{
        background-color: #ff3b3b;
        opacity: 1;
        color: #f4f4f4;
    }
    .is-red-{
        background-color: #ff3b3b;
        opacity: 0.9;
        color: #f4f4f4;
    }
    .is-red-:hover{
        background-color: #ff3b3b;
        opacity: 1;
        color: #f4f4f4;
    }
    @media screen and (max-width: 768px){
        div.columns.is-variable.is-centered#container-{
            justify-content: center;
            align-items: center;
            display: flex;
            flex-direction: column-reverse;
            }

        .button.is-red{
            font-size: 1rem;
        }
    }
    #menu{
        transform: translateX(100%);
    }
    #menu.active{
        transition: translateX(0%);
    }

</style>

    <section>
        <div class="container">
            <h1 class="title is-1 has-text-centered"> Welcome <span style="color: #ff3b3b;">{{ request.user }}</span>  </h1>
            <hr>
            <h5 class="title is-5 has-text-centered">Some of the URLs shorten by you are listed below</h5>
        
            <table class="table has-text-centered">
                <thead>
                  <tr>
                    <th><abbr title="Position">S No.</abbr></th>
                    <th>URL</th>
                  </tr>
                </thead>
                
                <tbody>
                    {% for url in all_urls %}
                  <tr>
                    <th> {{ forloop.counter }} </th>
                    <td>  <a href="//{{ url.short_url }}" target="_blank"> {{ url.short_url }}</a> </td>
                    </tr>
                    {% endfor %}
                </tbody>


              </table> 
        </div>
    </section>


{% endblock body %}

mainApp/templates/expired.html
{% extends 'base.html' %}
{% block title %} Url Expired {% endblock title %}

{% block body %}

<h1>The URL you are trying to reach has been expired or it is not yet created.</h1>

{% endblock body %}

mainApp/templates/index.html
{% extends 'base.html' %}
{% block title %} Home {% endblock title %}
{% block body %}
{% load static %}

<style>
    *{
        scroll-behavior: smooth;
    }
    .is-red{
        background-color: #ff3b3b;
        opacity: 0.9;
        color: #f4f4f4;
    }
    .is-red:hover{
        background-color: #ff3b3b;
        opacity: 1;
        color: #f4f4f4;
    }
    .is-red-{
        background-color: #ff3b3b;
        opacity: 0.9;
        color: #f4f4f4;
    }
    .is-red-:hover{
        background-color: #ff3b3b;
        opacity: 1;
        color: #f4f4f4;
    }
    @media screen and (max-width: 768px){
        div.columns.is-variable.is-centered#container-{
            justify-content: center;
            align-items: center;
            display: flex;
            flex-direction: column-reverse;
            }

        .button.is-red{
            font-size: 1rem;
        }
    }


</style>

<section class="section">
    <div class="conatiner">
        <div class="columns is-variable is-centered" id="container-">
            <div class="column is-7">
                <div class="card" style="box-shadow:none;">
                    <div class="card-content">
                        <h2 class="is-size-1 is-size-3-tablet is-size-3-mobile" style="font-weight: 550;"><strong>Shorten Your Long URL</strong></h2>

                        <p class="is-size-5 mt-4 is-size-6-tablet is-size-6-mobile" style="color: #666666;">DUS is a shortening and link management platform to Brand,<br> Track and Share short URLs using a custom path.</p>
                        <div class="fields mt-6"><a class="button is-red is-normal-mobile is-medium is-normal-mobile is-normal-tablet" href="#short_section">Get Started</a></div>

                    </div>
                </div>
            </div>
            <div class="column is-two-fifths is-three-quarters-mobile" >
                <div class="card" style="box-shadow:none;">
                    <div class="card-image"><img src="{% static 'assets/img/undrawimg.svg' %}" alt=""></div>
                </div>
            </div>
        </div>
    </div>
</section>


{% if short_url %}
<div class="container mt-4">
  <div class="notification is-primary">
    Your Short Url : <input type="text" class="input is-small" style="width: 50%; background: transparent; color: white; border: none;" value="{{ short_url }}" id="shorted_url"> 
    <div class="is-pulled-right">
        <button class="button is-small is-outlined is-rounded" onclick="copyUrl()">Copy</button>
    </div>
  </div>
</div>
<script>
    function copyUrl(){
        let holdText = document.getElementById("shorted_url");
        let textToCopy = holdText.value;
        navigator.clipboard.writeText(textToCopy);
        alert("Copied Url : " + textToCopy);
    }

</script>
{% endif %}


<section class="section" id="short_section" style="background-color: #f4f4f4;">
    <form action="short" method="POST" id="form">
        {% csrf_token  %}
        <div class="conatiner">
            <div class="columns is-variable is-centered">
                <div class="column is-one-thirds">
                    <div class="fields">
                        <input class="input is-medium" type="text" placeholder="Enter Your URL here" name="original_url" required>
                        <input type="text" class="input is-small mt-2" id="custom_url" name="custom_url" placeholder="Enter custom url"/>
                    </div>
                </div>
            </div>
            <div class="column is-one-fifth">
                <div class="buttons" style="justify-content: center;"><button type="submit" class="button is-medium input is-red-" >Shorten</button></div>
            </div>
        </div>
    </form>
     <label class="checkbox mt-2 ml-1">
            <input type="checkbox" onchange="handleChange(this)" id="custom_check" />
            Want Custom URL?
        </label>
</section>



<script>
    let elem = document.getElementById("custom_url");
    elem.style.display = "none";

    function handleChange(cBox){
        let custom_input = document.getElementById("custom_url");
        if(cBox.checked){
            custom_input.style.display = "block";
        }
        else{
            custom_input.style.display = "none";
        }
    }
    
</script>

{% endblock body %}